### ISSUE TITLE
Build failed on windows

### ISSUE THREAD

**Issue by limuy2022** [gettext-rs/gettext-rs#118] opened 2024-02-05 08:25 UTC
I tried building it on windows straightly,but I met an error about tar.Then I tried use "cross-compilation" on Arch Linux,but a new error happened.
The following is the error infomation

/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: hello.o: in function `main':
  /tmp/t61385-0/gettext/libtextstyle/adhoc-tests/hello.c:60: undefined reference to `libtextstyle_isatty'
  collect2: error: ld returned 1 exit status
  make[4]: *** [Makefile:1567：hello.exe] error 1
  make[3]: *** [Makefile:1786：all-recursive] error 1
  make[2]: *** [Makefile:1714：all] error 2
  make[1]: *** [Makefile:403：all-recursive] error 1
  make: *** [Makefile:359：all] error 2
  thread 'main' panicked at /home/limuy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gettext-sys-0.21.3/build.rs:300:5:

By the way,is this project still under development?

**Comment by Minoru** [comment] 2024-07-20 15:17
From this snippet, it looks like `./configure` failed to build something. I'd try building gettext manually following the same steps as in gettext-sys/build.rs, so you have better control over what's going on and can poke at it. Once you've figured out the cause, perhaps you'd be able to update gettext-sys/build.rs to fix the failure.

The `tar` issue is tracked in #12. I expect to make a new release next week, where I'll replace the tarball with a directory. It probably won't solve all Windows issues, but I hope it'd help.

The project *is* under development again :)

**Comment by limuy2022** [comment] 2024-07-21 14:22
Congratulate!Glad to see gettext-rs be under development again.But I have turned to rust-i18n crate.I hoped one day I can use gettext-rs in my new project again.

**Comment by Minoru** [comment] 2024-07-23 21:10
I actually think it's good to switch to Rust-native internationalization libraries. In my view, gettext-rs is for situations where you *have* to use gettext. For instance, I use it in a project written in C++ which I'm porting to Rust; I use gettext-rs there to avoid having two separate translation workflows for the two languages. Once the program is fully in Rust, I'd strongly consider moving to some other library to avoid dependency on gettext.

Closing this since there's no apparent reason to delve into and fix this. If some other user stumbles into this, we can always re-open.

**Closed by Minoru** 2024-07-23 21:10 UTC
Labels: help wanted, bulid
